go_postgres_database:
  host: 35.197.146.208
  user: postgres
  password: "@bcd1@34"
  name: phoenix
  debug: true

paging:
  limit: 100

encryption:
  oid_key: ghnexp0123456789
  jwt_secret: secret
  jwt_secret_partner: secret
  jwt_exp: 72
  jwt_pol: 59a795909e65177c27fcdd87

